### ISSUE TITLE
Scrap Images From Google

### ISSUE THREAD

**Issue by ThisIsYuu** [ThisIsYuu/DataScrapper#3]
Currently it scarps images from twitter only

**Comment by hv-ojha** [comment]
So the issue isn't solved?

**Comment by hv-ojha** [comment]
Currently you are retrieving image from twitter but now you want google image search result...

Is this you want to say?

**Comment by ThisIsYuu** [comment]
@hv-ojha Yeah I want images from both twitter and google for a given query

**Comment by hv-ojha** [comment]
Okay I'll do it... 😊

**Comment by ThisIsYuu** [comment]
@nimah79 @nimah79 Thank You🙂
